from fey.fey_types.fey_types import Singleton, FeyDataclass, Point2D, Box2D


class Singleton(Singleton): ...
class FeyDataclass(FeyDataclass): ...
class Point2D(Point2D): ...
class Box2D(Box2D): ...
